name: "Build"
on:
  push:
  workflow_dispatch:

env:
  DEV_IMAGE_NAME: hung6876/react-remix
  VERSION: 1.0.0

jobs:
  test-export-env:
    runs-on: ubuntu-latest
    steps:
      - name: "Set Environment Variables"
        run: |
          echo "BUILD_NUMBER=$VERSION-npm" >> $GITHUB_ENV
          echo $BUILD_NUMBER
      - name: "Print Environment Variables"
        run: echo $BUILD_NUMBER
  lint:
    name: Lint
    uses: ./.github/workflows/linter.yml
    permissions:
      contents: read  
      packages: read
      statuses: write
    
  build:
    # needs: [lint]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "NodeJS Setup"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: "Npm Cache of ./node_modules"
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-npm
          path: node_modules

      - name: "Install Dependencies"
        run: npm install

      - name: "Unit Test"
        run: npm run test

      - name: "Build"
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hung6876
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: "Docker Setup Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Docker Build and Push"
        id: docker-build
        uses: docker/build-push-action@v5
        with:
          push: true
          file: docker/Dockerfile
          context: "."
          tags: ${{ env.DEV_IMAGE_NAME }}:${{ env.VERSION }}
      
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
