name: Test workflow name
run-name: Deploy NonProd ${{ github.ref_name }}
on:
  push:
  
jobs:
  test-checkout:
    name: Test Checkout
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Test workflow name
        run: |
          echo "Test workflow name"