name: "PR-target"
on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'dependabot/**'
jobs:
  pr-target:
    name: pr-target
    runs-on: ubuntu-latest

    steps:
      - name: "ECHO"
        run: echo "running pr-target"