name: Release NonProd
run-name: Deploy ${{ github.ref_name }} to NonProd
on:
  push:
    branches:
      - "release-*"
  
jobs:
  deploy-nonprod:
    name: ${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version
        uses: ./.github/actions/version
      
      - name: Deploy to NonProd
        run: |
          echo "Deploying to NonProd"
          echo "Version: $VERSION"
          echo "Major Version: $MAJOR_VERSION"
          echo "Minor Version: $MINOR_VERSION"
          echo "Patch Version: $PATCH_VERSION"
      
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: gh release edit "${VERSION}" --draft=false --prerelease=false --latest=true