name: Edit GitHub Release Status

on:
  release:
    types:
      - created

jobs:
  edit-release-status:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Edit release status
        uses: actions/github-script@v7
        with:
          script: |
            const release = context.payload.release;
            const response = await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              draft: false,
            });