name: Release

on:
  release:
    types:
      - created
  

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version
        uses: ./.github/actions/version

      - name: Mark Release as Draft
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: gh release edit "${VERSION}" --draft=true

      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev"
          echo "Version: $VERSION"
          echo "Major Version: $MAJOR_VERSION"
          echo "Minor Version: $MINOR_VERSION"
          echo "Patch Version: $PATCH_VERSION
  
  deploy-nonprod:
    name: Deploy to NonProd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version
        uses: ./.github/actions/version

      - name: Mark Release as Pre-Release
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: gh release edit "${VERSION}" --draft=false --prerelease=true

      - name: Deploy to NonProd
        run: |
          echo "Deploying to NonProd"
          echo "Version: $VERSION"
          echo "Major Version: $MAJOR_VERSION"
          echo "Minor Version: $MINOR_VERSION"
          echo "Patch Version: $PATCH_VERSION
      
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: gh release edit "${VERSION}" --draft=false --prerelease=false --latest=true