name: "Create Tag and Release"
on:
  pull_request_target:
    types:
      - "closed"
    branches:
      - "main"

jobs:
  create-release:
    if: github.event.pull_request.merged == true
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Version
        uses: ./.github/actions/version

      - name: GitHub Create Release
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git tag "${VERSION}"
          git push origin "${VERSION}"

          gh release create "${VERSION}" -t "${VERSION}" --generate-notes --verify-tag
      
      - name: Increment Version
        run: |
          python3 update_version.py
          VERSION=$(jq -r '.version' "package.json")
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add package.json
          git commit -m "[skip ci] Increment version to ${VERSION} by GitHub Actions"
          git push origin main
