name: Test Checkout

on:
  push:
  
jobs:
  test-checkout:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          depth: 0

      - name: Version
        uses: ./.github/actions/version
      
      - name: Test check branch
        run: |
          RELEASE_BRANCH="release-${MAJOR_VERSION}.${MINOR_VERSION}"

          git show-ref 

          if git show-ref --quiet "$RELEASE_BRANCH"; then
            echo "Branch '$RELEASE_BRANCH' already exists."
            echo "Updating branch '$RELEASE_BRANCH' with version '$VERSION'"

            # git checkout "$RELEASE_BRANCH"
            # git merge $VERSION
            # git push origin "$RELEASE_BRANCH"

            echo "Branch '$RELEASE_BRANCH' updated."

          else
            echo "Branch '$RELEASE_BRANCH' does not exist."
            echo "Creating branch '$RELEASE_BRANCH' with version '$VERSION'"

            # git checkout -b "$RELEASE_BRANCH" $VERSION
            # git push --set-upstream origin "$RELEASE_BRANCH"

            echo "Branch '$RELEASE_BRANCH' created."
          fi